### ISSUE TITLE
XMPlus server connection logs for debug

### ISSUE THREAD

**Issue by dadashali61** [xcode75/XMPlusDocs#2]
How can we check logs to debug connections? in XMPlus log option on the menu, there is nothing about that. I  made several connections even if it is green (connected) but I can't get any ping via "https://tcp.ping.pe/" and all connections will be refused if I setup another Xray server on it so everything is ok!

**Comment by xcode75** [comment]
> How can we check logs to debug connections? in XMPlus log option on the menu, there is nothing about that. I made several connections even if it is green (connected) but I can't get any ping via "https://tcp.ping.pe/" and all connections will be refused if I setup another Xray server on it so everything is ok!

Do not open an issue here, open issue on the backend repo XMPlus and provide details with a screenshot.
